apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cart
      project: roboshop
      tier: app

  template:
    metadata:
      labels:
        app: cart
        project: roboshop
        tier: app   
    spec:
     imagePullPolicy: Always
     containers:
      - name:  cart
        image: raviraveen/cart:v1
        envFrom:
          - configMapRef:
            name: cart
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
data: 
 MONGO:  "true"


---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: cart
selector:
    app: cart
    project: roboshop
    tier: app
    ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080  #container port
