apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
    imagePullPolicy: Always
    containers:
      - name:  mongodb
        image: raviraveen/mongodb:v1
        

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  selector:
    app: mongodb
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 27017 #service port
    targetPort: 27017  #container port
