apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: db
    spec:
    imagePullPolicy: Always
    containers:
      - name:  redis
        image: redis
        

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  selector:
    app: redis
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 6379 #service port
    targetPort: 6379 #container port
